FROM python:3.11-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

ENV PYTHONUNBUFFERED=1
COPY src ./src
ENV PYTHONPATH=/app

CMD ["python","-m","src.nodes.base_node"]